CREATE TABLE avro_test

ROW FORMAT

SERDE 'org.apache.hadoop.hive.serde2.avro.AvroSerDe'

STORED AS

INPUTFORMAT 'org.apache.hadoop.hive.ql.io.avro.AvroContainerInputFormat'

OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.avro.AvroContainerOutputFormat'

TBLPROPERTIES ('avro.schema.literal'='{

    "namespace": "AVRO", 

    "type": "record", 

    "name": "sampleAvro", 

    "fields": [

        {

            "type": "string", 

            "name": "name"

        }, 

        {

            "type": "int", 

            "name": "age"

        }, 

        {

            "type": "string", 

            "name": "address"

        }, 

        {

            "type": "long", 

            "name": "value"

        }

    ]

}')

;
